### ISSUE TITLE
Your build silently fails on travis

### ISSUE THREAD

**Issue by EECOLOR** [vi/execfuse#1]
I just noticed the following line in your build:

```
% fusermount -u m
fusermount: unable to open fuse lock file: Permission denied
```

**Comment by vi** [comment]
Fixed by using `umount` instead of `fusermount -u` when running the test as root.

**Comment by EECOLOR** [comment]
If you look at https://travis-ci.org/vi/execfuse/builds/69742151 you can see it now silently fails on two problems

**Comment by vi** [comment]
There was a problem `id -i` instead of `id -u`.

**Comment by vi** [comment]
Now I see no failures. Why unmounting is so important when checking in Travis?

**Comment by EECOLOR** [comment]
Oh, it was just a courtesy call. I came across your build by accident and noticed there was an error that was not detected. I am not experienced in `sh` so I thought it might be interesting for you to know. I did not look at the nature of the problem.
